name: Daily render ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Check allowed time window
        run: |
          current_hour=$(date -u +"%H")
          current_minute=$(date -u +"%M")
          current_day=$(date -u +"%u") # 1=Mon, 7=Sun

          # Skip if between 21:00-22:00 UTC any day
          if [ "$current_hour" -eq 21 ]; then
            echo "Skipping between 21:00-22:00 UTC."
            exit 0
          fi

          # Skip if Friday 21:00 UTC → Sunday 22:00 UTC
          if { [ "$current_day" -eq 5 ] && [ "$current_hour" -ge 21 ]; } || \
             [ "$current_day" -eq 6 ] || \
             { [ "$current_day" -eq 7 ] && [ "$current_hour" -lt 22 ]; }; then
            echo "Skipping weekend downtime window."
            exit 0
          fi

      - name: Run cURL on Website
        run: curl -I https://hui-2.onrender.com
